version: "3.3"

services:
  mariadb:
    image: "bitnami/mariadb:10.3"
    restart: always
    networks:
      - moodle-net
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/home/moodle_db:/bitnami:z'
    ports:
      - "3306:3306"

  moodle:
    image: "webdevops/php-apache:7.3"
    restart: always
    networks:
      - moodle-net
    environment:
      - MOODLE_DBHOST=mariadb
      - MOODLE_DBPORT=3306
      - MOODLE_DBUSER=bn_moodle
      - MOODLE_DBPASS=''
      - MOODLE_DBNAME=bitnami_moodle
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '/home/moodledata:/moodledata/moodledata:z'
      - '/home/moodle_source/moodle:/app:z'
    depends_on:
      - mariadb

networks:
  moodle-net:
    driver: bridge
